version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: paper_summarizer_test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d paper_summarizer_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://testuser:testpass@postgres:5432/paper_summarizer_test
      - SECRET_KEY=test-secret-key-for-docker
      - OPENAI_API_KEY=test-openai-key
      - GROQ_API_KEY=test-groq-key
      - ENVIRONMENT=development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./research_papers:/app/research_papers

volumes:
  postgres_data:
