services:
  - type: web
    name: paper-summarizer-backend
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: https://your-frontend-app.vercel.app,http://localhost:3000
      - key: PORT
        value: 8001
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY  
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: REDIS_URL
        sync: false
    disk:
      name: paper-storage
      sizeGB: 1
      mountPath: /app/research_papers
